### ISSUE TITLE
dataset is not supported in IE10. Do mind that. IE10 EOL till April 2020

### ISSUE THREAD

**Issue by soulman-is-good** [Amomentforever0/components#2]
https://github.com/Amomentforever0/components/blob/7a6f99eb0a7c7cbe72488fcbd3b2eae2ca6b7b6f/Tooltip/app.js#L35

**Comment by Amomentforever0** [comment]
> https://github.com/Amomentforever0/components/blob/7a6f99eb0a7c7cbe72488fcbd3b2eae2ca6b7b6f/Tooltip/app.js#L35

replaced with getAttribute, which support is much better 👍  thank you!
